// Generated by npm run visuals:registry. Do not edit by hand.
import asset0 from '../assets/lesson-visuals/blocks/lesson-01-step-04.svg';
import asset1 from '../assets/lesson-visuals/blocks/lesson-02-step-02.svg';
import asset2 from '../assets/lesson-visuals/blocks/lesson-03-step-01.svg';
import asset3 from '../assets/lesson-visuals/blocks/lesson-03-step-02.svg';
import asset4 from '../assets/lesson-visuals/blocks/lesson-03-step-05.svg';
import asset5 from '../assets/lesson-visuals/blocks/lesson-03-step-06.svg';
import asset6 from '../assets/lesson-visuals/blocks/lesson-04-step-01.svg';
import asset7 from '../assets/lesson-visuals/blocks/lesson-04-step-02.svg';
import asset8 from '../assets/lesson-visuals/blocks/lesson-04-step-04.svg';
import asset9 from '../assets/lesson-visuals/blocks/lesson-04-step-05.svg';
import asset10 from '../assets/lesson-visuals/blocks/lesson-05-step-01.svg';
import asset11 from '../assets/lesson-visuals/blocks/lesson-05-step-02.svg';
import asset12 from '../assets/lesson-visuals/blocks/lesson-05-step-03.svg';
import asset13 from '../assets/lesson-visuals/blocks/lesson-05-step-04.svg';
import asset14 from '../assets/lesson-visuals/blocks/lesson-05-step-06.svg';
import asset15 from '../assets/lesson-visuals/blocks/lesson-06-step-01.svg';
import asset16 from '../assets/lesson-visuals/blocks/lesson-06-step-02.svg';
import asset17 from '../assets/lesson-visuals/blocks/lesson-06-step-03.svg';
import asset18 from '../assets/lesson-visuals/blocks/lesson-06-step-04.svg';
import asset19 from '../assets/lesson-visuals/blocks/lesson-06-step-05.svg';
import asset20 from '../assets/lesson-visuals/blocks/lesson-07-step-01.svg';
import asset21 from '../assets/lesson-visuals/blocks/lesson-07-step-02.svg';
import asset22 from '../assets/lesson-visuals/blocks/lesson-07-step-03.svg';
import asset23 from '../assets/lesson-visuals/blocks/lesson-07-step-04.svg';
import asset24 from '../assets/lesson-visuals/blocks/lesson-07-step-05.svg';
import asset25 from '../assets/lesson-visuals/blocks/lesson-08-step-01.svg';
import asset26 from '../assets/lesson-visuals/blocks/lesson-08-step-02.svg';
import asset27 from '../assets/lesson-visuals/blocks/lesson-08-step-03.svg';
import asset28 from '../assets/lesson-visuals/blocks/lesson-08-step-04.svg';
import asset29 from '../assets/lesson-visuals/blocks/lesson-08-step-05.svg';
import asset30 from '../assets/lesson-visuals/blocks/lesson-09-step-01.svg';
import asset31 from '../assets/lesson-visuals/blocks/lesson-09-step-02.svg';
import asset32 from '../assets/lesson-visuals/blocks/lesson-09-step-03.svg';
import asset33 from '../assets/lesson-visuals/blocks/lesson-09-step-04.svg';
import asset34 from '../assets/lesson-visuals/blocks/lesson-09-step-05.svg';
import asset35 from '../assets/lesson-visuals/blocks/lesson-10-step-01.svg';
import asset36 from '../assets/lesson-visuals/blocks/lesson-10-step-02.svg';
import asset37 from '../assets/lesson-visuals/blocks/lesson-10-step-03.svg';
import asset38 from '../assets/lesson-visuals/blocks/lesson-10-step-04.svg';
import asset39 from '../assets/lesson-visuals/blocks/lesson-10-step-05.svg';
import asset40 from '../assets/lesson-visuals/blocks/lesson-11-step-01.svg';
import asset41 from '../assets/lesson-visuals/blocks/lesson-11-step-02.svg';
import asset42 from '../assets/lesson-visuals/blocks/lesson-11-step-03.svg';
import asset43 from '../assets/lesson-visuals/blocks/lesson-11-step-04.svg';
import asset44 from '../assets/lesson-visuals/blocks/lesson-11-step-06.svg';
import asset45 from '../assets/lesson-visuals/blocks/lesson-12-step-01.svg';
import asset46 from '../assets/lesson-visuals/blocks/lesson-12-step-02.svg';
import asset47 from '../assets/lesson-visuals/blocks/lesson-12-step-03.svg';
import asset48 from '../assets/lesson-visuals/blocks/lesson-12-step-04.svg';
import asset49 from '../assets/lesson-visuals/blocks/lesson-12-step-05.svg';
import asset50 from '../assets/lesson-visuals/blocks/lesson-13-step-01.svg';
import asset51 from '../assets/lesson-visuals/blocks/lesson-13-step-04.svg';
import asset52 from '../assets/lesson-visuals/blocks/lesson-13-step-05.svg';
import asset53 from '../assets/lesson-visuals/blocks/lesson-13-step-06.svg';
import asset54 from '../assets/lesson-visuals/blocks/lesson-14-step-04.svg';
import asset55 from '../assets/lesson-visuals/blocks/lesson-14-step-05.svg';
import asset56 from '../assets/lesson-visuals/blocks/lesson-15-step-01.svg';
import asset57 from '../assets/lesson-visuals/blocks/lesson-15-step-02.svg';
import asset58 from '../assets/lesson-visuals/blocks/lesson-15-step-03.svg';
import asset59 from '../assets/lesson-visuals/blocks/lesson-15-step-04.svg';
import asset60 from '../assets/lesson-visuals/blocks/lesson-15-step-05.svg';
import asset61 from '../assets/lesson-visuals/blocks/lesson-15-step-06.svg';
import asset62 from '../assets/lesson-visuals/blocks/lesson-16-step-02.svg';
import asset63 from '../assets/lesson-visuals/blocks/lesson-16-step-03.svg';
import asset64 from '../assets/lesson-visuals/blocks/lesson-16-step-04.svg';
import asset65 from '../assets/lesson-visuals/blocks/lesson-16-step-05.svg';
import asset66 from '../assets/lesson-visuals/blocks/lesson-16-step-06.svg';
import asset67 from '../assets/lesson-visuals/editor/animation-extension.webp';
import asset68 from '../assets/lesson-visuals/editor/animation-frames.webp';
import asset69 from '../assets/lesson-visuals/editor/arcade-home.webp';
import asset70 from '../assets/lesson-visuals/editor/blocks-workspace.webp';
import asset71 from '../assets/lesson-visuals/editor/sprite-image-editor.webp';
import asset72 from '../assets/lesson-visuals/editor/tilemap-editor.webp';

export const lessonVisualAssets = {
  'blocks:lesson-01-step-04': { kind: 'blocks', src: asset0 },
  'blocks:lesson-02-step-02': { kind: 'blocks', src: asset1 },
  'blocks:lesson-03-step-01': { kind: 'blocks', src: asset2 },
  'blocks:lesson-03-step-02': { kind: 'blocks', src: asset3 },
  'blocks:lesson-03-step-05': { kind: 'blocks', src: asset4 },
  'blocks:lesson-03-step-06': { kind: 'blocks', src: asset5 },
  'blocks:lesson-04-step-01': { kind: 'blocks', src: asset6 },
  'blocks:lesson-04-step-02': { kind: 'blocks', src: asset7 },
  'blocks:lesson-04-step-04': { kind: 'blocks', src: asset8 },
  'blocks:lesson-04-step-05': { kind: 'blocks', src: asset9 },
  'blocks:lesson-05-step-01': { kind: 'blocks', src: asset10 },
  'blocks:lesson-05-step-02': { kind: 'blocks', src: asset11 },
  'blocks:lesson-05-step-03': { kind: 'blocks', src: asset12 },
  'blocks:lesson-05-step-04': { kind: 'blocks', src: asset13 },
  'blocks:lesson-05-step-06': { kind: 'blocks', src: asset14 },
  'blocks:lesson-06-step-01': { kind: 'blocks', src: asset15 },
  'blocks:lesson-06-step-02': { kind: 'blocks', src: asset16 },
  'blocks:lesson-06-step-03': { kind: 'blocks', src: asset17 },
  'blocks:lesson-06-step-04': { kind: 'blocks', src: asset18 },
  'blocks:lesson-06-step-05': { kind: 'blocks', src: asset19 },
  'blocks:lesson-07-step-01': { kind: 'blocks', src: asset20 },
  'blocks:lesson-07-step-02': { kind: 'blocks', src: asset21 },
  'blocks:lesson-07-step-03': { kind: 'blocks', src: asset22 },
  'blocks:lesson-07-step-04': { kind: 'blocks', src: asset23 },
  'blocks:lesson-07-step-05': { kind: 'blocks', src: asset24 },
  'blocks:lesson-08-step-01': { kind: 'blocks', src: asset25 },
  'blocks:lesson-08-step-02': { kind: 'blocks', src: asset26 },
  'blocks:lesson-08-step-03': { kind: 'blocks', src: asset27 },
  'blocks:lesson-08-step-04': { kind: 'blocks', src: asset28 },
  'blocks:lesson-08-step-05': { kind: 'blocks', src: asset29 },
  'blocks:lesson-09-step-01': { kind: 'blocks', src: asset30 },
  'blocks:lesson-09-step-02': { kind: 'blocks', src: asset31 },
  'blocks:lesson-09-step-03': { kind: 'blocks', src: asset32 },
  'blocks:lesson-09-step-04': { kind: 'blocks', src: asset33 },
  'blocks:lesson-09-step-05': { kind: 'blocks', src: asset34 },
  'blocks:lesson-10-step-01': { kind: 'blocks', src: asset35 },
  'blocks:lesson-10-step-02': { kind: 'blocks', src: asset36 },
  'blocks:lesson-10-step-03': { kind: 'blocks', src: asset37 },
  'blocks:lesson-10-step-04': { kind: 'blocks', src: asset38 },
  'blocks:lesson-10-step-05': { kind: 'blocks', src: asset39 },
  'blocks:lesson-11-step-01': { kind: 'blocks', src: asset40 },
  'blocks:lesson-11-step-02': { kind: 'blocks', src: asset41 },
  'blocks:lesson-11-step-03': { kind: 'blocks', src: asset42 },
  'blocks:lesson-11-step-04': { kind: 'blocks', src: asset43 },
  'blocks:lesson-11-step-06': { kind: 'blocks', src: asset44 },
  'blocks:lesson-12-step-01': { kind: 'blocks', src: asset45 },
  'blocks:lesson-12-step-02': { kind: 'blocks', src: asset46 },
  'blocks:lesson-12-step-03': { kind: 'blocks', src: asset47 },
  'blocks:lesson-12-step-04': { kind: 'blocks', src: asset48 },
  'blocks:lesson-12-step-05': { kind: 'blocks', src: asset49 },
  'blocks:lesson-13-step-01': { kind: 'blocks', src: asset50 },
  'blocks:lesson-13-step-04': { kind: 'blocks', src: asset51 },
  'blocks:lesson-13-step-05': { kind: 'blocks', src: asset52 },
  'blocks:lesson-13-step-06': { kind: 'blocks', src: asset53 },
  'blocks:lesson-14-step-04': { kind: 'blocks', src: asset54 },
  'blocks:lesson-14-step-05': { kind: 'blocks', src: asset55 },
  'blocks:lesson-15-step-01': { kind: 'blocks', src: asset56 },
  'blocks:lesson-15-step-02': { kind: 'blocks', src: asset57 },
  'blocks:lesson-15-step-03': { kind: 'blocks', src: asset58 },
  'blocks:lesson-15-step-04': { kind: 'blocks', src: asset59 },
  'blocks:lesson-15-step-05': { kind: 'blocks', src: asset60 },
  'blocks:lesson-15-step-06': { kind: 'blocks', src: asset61 },
  'blocks:lesson-16-step-02': { kind: 'blocks', src: asset62 },
  'blocks:lesson-16-step-03': { kind: 'blocks', src: asset63 },
  'blocks:lesson-16-step-04': { kind: 'blocks', src: asset64 },
  'blocks:lesson-16-step-05': { kind: 'blocks', src: asset65 },
  'blocks:lesson-16-step-06': { kind: 'blocks', src: asset66 },
  'editor:animation-extension': { kind: 'editor', src: asset67 },
  'editor:animation-frames': { kind: 'editor', src: asset68 },
  'editor:arcade-home': { kind: 'editor', src: asset69 },
  'editor:blocks-workspace': { kind: 'editor', src: asset70 },
  'editor:sprite-image-editor': { kind: 'editor', src: asset71 },
  'editor:tilemap-editor': { kind: 'editor', src: asset72 },
} as const;

export type LessonVisualAssetId = keyof typeof lessonVisualAssets;
