// Generated by npm run visuals:registry. Do not edit by hand.
import asset0 from '../assets/lesson-visuals/blocks/lesson-01-step-04.svg';
import asset1 from '../assets/lesson-visuals/editor/animation-extension.webp';
import asset2 from '../assets/lesson-visuals/editor/animation-frames.webp';
import asset3 from '../assets/lesson-visuals/editor/arcade-home.webp';
import asset4 from '../assets/lesson-visuals/editor/blocks-workspace.webp';
import asset5 from '../assets/lesson-visuals/editor/sprite-image-editor.webp';
import asset6 from '../assets/lesson-visuals/editor/tilemap-editor.webp';

export const lessonVisualAssets = {
  'blocks:lesson-01-step-04': { kind: 'blocks', src: asset0 },
  'editor:animation-extension': { kind: 'editor', src: asset1 },
  'editor:animation-frames': { kind: 'editor', src: asset2 },
  'editor:arcade-home': { kind: 'editor', src: asset3 },
  'editor:blocks-workspace': { kind: 'editor', src: asset4 },
  'editor:sprite-image-editor': { kind: 'editor', src: asset5 },
  'editor:tilemap-editor': { kind: 'editor', src: asset6 },
} as const;

export type LessonVisualAssetId = keyof typeof lessonVisualAssets;
